on:
  push:
    paths:
      - .github/workflows/scrape.yml # Only run a new workflow every time thisfile changes
  schedule:
    - cron:  '0 * * * *' # Every hour. Ref https://crontab.guru/examples.html

env:
  DENO_DIR: my_cache_directory
name: Scrape Data
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x   
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Cache Deno dependencies 
      uses: actions/cache@v3
      with:
        path: ${{ env.DENO_DIR }}
        key: ${{ hashFiles('deno.lock') }} 
    - name: Scrape
      run: deno run --allow-all ./src/index.ts
    - name: Push changes if there are
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        BRANCH_NAME: main