on:
  push:
    paths:
      - .github/workflows/scrape.yml # Only run a new workflow every time thisfile changes
  schedule:
    - cron:  '0 * * * *' # Every hour. Ref https://crontab.guru/examples.html
name: Scrape Data
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x   
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Scrape
      run: deno run --allow-all ./src/index.ts
      # env:
      #   WHATEVER_TOKEN: ${{ secrets.YOU_WANT }}
    - name: Push changes if there are
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
        BRANCH_NAME: main